### ISSUE TITLE
RunTargetsAndExit() and RunTargetsAndExitAsync()

### ISSUE THREAD

**Issue by adamralph** [adamralph/bullseye#172]
These method groups will run the targets and then call `Environment.Exit`.

- The current `RunTargets()` and `RunTargetsAsync` will be deprecated.
- The .NET Standard 1.3 assembly will be removed, since `Environment.Exit()` does not exist in .NET Standard 1.3.

The advantage is that when an exception is thrown by Bullseye, the exception message will be logged and the process will exit with an appropriate exit code. Currently, the process exits with an unhandled exception, which results in the stack trace being written to the console, and an application error being written to the OS event log (at least on Windows) which usually results in a significant delay before control is returned to the console.

### `RunTargets(args)`

```
.\build.cmd -abc

Unhandled Exception: Bullseye.BullseyeException: Unknown option -abc. "--help" for usage.
   at Bullseye.Internal.TargetCollectionExtensions.RunAsync(TargetCollection targets, List`1 args, IConsole console) in C:\projects\bullseye\Bullseye\Internal\TargetCollectionExtensions.cs:line 180
   at Program.<Main>(String[] args)
```

And three entries in the OS event logs! Notice that two seconds elapsed between the first and last entry, and this seems to be the delay in control being returned to the console after the process exits.

<img src="https://user-images.githubusercontent.com/677704/49343434-60c01480-f669-11e8-809e-75adbd13bb69.png" width="200px" /><img src="https://user-images.githubusercontent.com/677704/49343438-6c134000-f669-11e8-887a-d52a9c724c4d.png" width="200px" /><img src="https://user-images.githubusercontent.com/677704/49343444-84835a80-f669-11e8-9685-69abf07eba17.png" width="200px" />

### `RunTargetsAndExit(args)`

```
.\build.cmd -abc
Unknown option -abc. "--help" for usage.
```

(Nothing in the OS event logs.)

## Overloads

There will be overloads for specifying further exception types which should only have their messages logged:

```c#
RunTargetsAndExit<T>(IEnumerable<string> args)
RunTargetsAndExit<T1, T2>(IEnumerable<string> args)
RunTargetsAndExit<T1, T2, T3>(IEnumerable<string> args)
RunTargetsAndExit<T1, T2, T3, T4>(IEnumerable<string> args)
RunTargetsAndExit(IEnumerable<string> args, IEnumerable<Type> exceptionMessageOnly)

RunTargetsAndExitAsync<T>(IEnumerable<string> args)
RunTargetsAndExitAsync<T1, T2>(IEnumerable<string> args)
RunTargetsAndExitAsync<T1, T2, T3>(IEnumerable<string> args)
RunTargetsAndExitAsync<T1, T2, T3, T4>(IEnumerable<string> args)
RunTargetsAndExitAsync(IEnumerable<string> args, IEnumerable<Type> exceptionMessageOnly)
```

**Comment by adamralph** [comment]
Released in [beta 3](https://www.nuget.org/packages/Bullseye/2.3.0-beta.3).

**Comment by adamralph** [comment]
Released in [beta 5](https://www.nuget.org/packages/Bullseye/2.3.0-beta.5).
